name: covid19-dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    
  cd:
   runs-on: ubuntu-latest

   steps:
     - uses: actions/checkout@v1
     - name: Docker login
       run: docker login ${{ secrets.DOCKER_URI }} -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
     - name: Build
       run: docker build -t "covid19-dashboard" .
     - name: Tags
       run: |
         docker tag covid19-dashboard ${{ secrets.DOCKER_URI }}/covid19-dashboard:${{ github.sha }}
         docker tag covid19-dashboard ${{ secrets.DOCKER_URI }}/covid19-dashboard:latest
     - name: Push
       run: |
          docker push ${{ secrets.DOCKER_URI }}/covid19-dashboard:${{ github.sha }}
          docker push ${{ secrets.DOCKER_URI }}/covid19-dashboard:latest

